---
- hosts: dbsystems
  become: yes
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
    - name: enabling httpd service and start the service
      service: 
        name: httpd
        enabled: yes
        state: started

      notify:
          - restart httpd service

  handlers:
    - name: restart httpd service          
      service:
        name: httpd
        state: restarted    

